name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: |
          chmod +x ./.github/workflows/secrets/decrypt_secrets.sh
          ./.github/workflows/secrets/decrypt_secrets.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: |
          chmod +x ./.github/workflows/scripts/archive_app.sh
          ./.github/workflows/scripts/archive_app.sh
      - name: Exporting .ipa
        run: |
          chmod +x ./.github/workflows/scripts/export_ipa.sh
          ./.github/workflows/scripts/export_ipa.sh
      - name:  gem install deploygate
        run: |
          gem install deploygate
          dg deploy AIO.ipa/AIO.ipa --email="giangdoanthe@gmail.com"

